name: Tests (Cucumber + Allure)
on:
  push: {branches: ["**"]}
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - uses: browser-actions/setup-chrome@v1
      - name: Run Cucumber tests
        env:
          CALC_URL: ${{ vars.CALC_URL || secrets.CALC_URL || 'https://example.com' }}
          HEADLESS: "true"
        run: mvn -B -q test
      - uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
